Output error message to STDERR
Signed-off-by: Fxzx mic <54622331+fxzxmic@users.noreply.github.com>

diff --git a/decode-base64 b/decode-base64
--- a/decode-base64
+++ b/decode-base64
@@ -7,7 +7,7 @@ else
 			printf "%s\n" $(printf "%s\n" "$param" | base64 -d)
 		done
 	else
-		echo "Parameter Error"
+		echo "Parameter Error" >&2
 		return 1
 	fi
 fi
diff --git a/decode-url b/decode-url
--- a/decode-url
+++ b/decode-url
@@ -8,7 +8,7 @@ else
 			printf "${i//%/\\x}\n"
 		done
 	else
-		echo "Parameter Error"
+		echo "Parameter Error" >&2
 		return 1
 	fi
 fi
diff --git a/encode-base64 b/encode-base64
--- a/encode-base64
+++ b/encode-base64
@@ -7,7 +7,7 @@ else
 			printf "%s" "$param" | base64
 		done
 	else
-		echo "Parameter Error"
+		echo "Parameter Error" >&2
 		return 1
 	fi
 fi
diff --git a/encode-url b/encode-url
--- a/encode-url
+++ b/encode-url
@@ -13,7 +13,7 @@ else
 			}')
 		done
 	else
-		echo "Parameter Error"
+		echo "Parameter Error" >&2
 		return 1
 	fi
 fi
diff --git a/lns b/lns
--- a/lns
+++ b/lns
@@ -9,7 +9,7 @@ else
 			ln -s "${1%*/}/$file" "${2%*/}/$file"
 		done
 	else
-		echo "Parameter Error"
+		echo "Parameter Error" >&2
 		return 1
 	fi
 fi
diff --git a/minifier b/minifier
--- a/minifier
+++ b/minifier
@@ -12,9 +12,9 @@ else
 	esac
 
 	if [ -n "$URL" -a -f "$2" -a -r "$2" -a -f "$3" -a -w "$3" ]; then
-		curl -X POST -s --data-urlencode "input=$(cat "$2")" $URL -o "$(wslpath -m "$3")"
+		curl -X POST -s --data-urlencode "input=$(cat "$2")" $URL -o "$(wslpath -m "$3")" --fail
 	else
-		echo "Parameter Error"
+		echo "Parameter Error" >&2
 		return 1
 	fi
 fi
